### ISSUE TITLE
Issue on Native and Web Based Checkout

### ISSUE THREAD

**Issue by antonino-tocco** [paypal/paypalcheckout-android#7]
Hi all, when I want to checkout I have this issue.
In native mode the app crash due to: 
2019-03-23 10:36:28.238 3204-3204/com.easytour.easytour E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.easytour.easytour, PID: 3204
    java.lang.ExceptionInInitializerError
        at com.paypal.authcore.util.TokenState.getInstance(TokenState.java:19)
        at com.paypal.authcore.authentication.Authenticator.authenticateForAccessTokenWithDelegate(Authenticator.java:123)
        at com.paypal.pyplcheckout.PYPLCheckout.logInUser(PYPLCheckout.java:291)
        at com.paypal.pyplcheckout.PYPLInitiateCheckout.onCreate(PYPLInitiateCheckout.java:32)
        at android.app.Activity.performCreate(Activity.java:7372)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1218)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3147)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3302)
        at android.app.ActivityThread.-wrap12(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1891)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7425)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.SharedPreferences android.content.Context.getSharedPreferences(java.lang.String, int)'

In web based checkout instead the web view open but give me that I'm not connected and I do return to merchant website.
Can you help me?

**Comment by dmikey** [comment]
Hi @antonino-tocco! Can you share with us a bit more about what you are doing to attempt to get to this route?
